language: cpp
# compiler:
#   - clang
#   - gcc
# branches:
#   only:
#   - master
#   - travis_ci
os:
  - linux
  - osx
  # - windows
jdk:
  - oraclejdk8
addons:
  apt:
    packages: csh
  # homebrew:
  #   packages: csh
before_install:
  - pip install --user codecov
script:
  - make all libraries
  - pip install --user python2_bindings/
  - cd unit_test
  - make all
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./run_all_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then csh run_all_tests.sh; fi
after_success:
  - gcovr -r obj/ -e '.*?hpp' -e '.*?hh' --xml -o coverage.xml
#  - bash <(curl -s https://codecov.io/bash)
  - codecov --file coverage.xml --disable search
