language: cpp
# compiler:
#   - clang
#   - gcc
# branches:
#   only:
#   - master
#   - travis_ci
addons:
  apt:
    packages: csh
  # homebrew:
  #   packages: csh
script:
  - make all libraries
  - pip install --user python2_bindings/
  - cd unit_test
  - make all
  - csh run_all_tests.sh

