language: cpp
compiler:
  - clang
  - gcc
branches:
  only:
  - master
  - travis_ci
script:
  - make all libraries
  - pip install --user python2_bindings
  - unit_test
  - make all
  - bash run_all_tests.sh

