language: cpp
# compiler:
#   - clang
#   - gcc
# branches:
#   only:
#   - master
#   - travis_ci
os:
  - linux
  - osx
  # - windows
env:
  - CODECOV_TOKEN="d02d94b5-2584-4ed9-8eb5-8a3bcda19af8"
jdk:
  - oraclejdk8
addons:
  apt:
    packages: 
    - csh
    - gcovr
before_install:
  - pip install --user codecov
script:
  - make all libraries CPPFLAGS=--coverage
  - pip install --user python2_bindings/
  - cd unit_test
  - make all CPPFLAGS=-fprofile-arcs -ftest-coverage
#  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./run_all_tests.bat; fi
#  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then csh run_all_tests.sh; fi
  - csh run_all_tests.sh
after_success:
  - gcovr -r ../ --filter ../src/ --xml -o coverage.xml 
#  - gcovr -r ../obj/ -e '.*?hpp' -e '.*?hh' -r ../ --xml -o coverage.xml
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml -X gcov -X fix
