language: cpp
# compiler:
#   - clang
#   - gcc
# branches:
#   only:
#   - master
#   - travis_ci
os:
  # - linux
  - osx
addons:
  apt:
    packages: csh
  # homebrew:
  #   packages: csh
script:
  - make -j2 all libraries
  - pip install --user python2_bindings/
  - cd unit_test
  - make -j2 all
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./run_all_tests.bat; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then csh run_all_tests.sh; fi

